### ISSUE TITLE
idea 

### ISSUE THREAD

**Issue by ZeDiogoAraujo** [vaxxi/iqos#1]
i like to talk with you man

**Comment by vaxxi** [comment]
What about ?

**Comment by ZeDiogoAraujo** [comment]
i have an idea can speak in private

**Comment by ZeDiogoAraujo** [comment]
i can use iqos like a usb pen ?

2018-05-03 13:45 GMT+01:00 vaxxi <notifications@github.com>:

**Comment by vaxxi** [comment]
I've received your email - very unlikely to do what you want.

**Comment by dzintarssmilga** [comment]
Is it possible to find some kind of android app, not stock IQOS but something advanced?

**Comment by vaxxi** [comment]
Highly unlikely, unless somebody reverse engineers the BT communication.

**Comment by mluis** [comment]
Just revisiting this.. it seems there's already something. 
https://github.com/0x77dev/iqos.web
